[package]
name = "suns"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.0"
tap = "1.0.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
actix-web = "4.2.1"
futures = "0.3.24"